### ISSUE TITLE
Unexpected warning message when value contains wrong format

### ISSUE THREAD

**Issue by PeterCervienka** [relekang/validator#12]
I am getting a warning

> Thu, 19 May 2016 07:05:23 GMT validator deprecated you tried to validate a number but this library (validator.js) validates strings only. Please update your code as this will be an error soon. at node_modules\@relekang\validator\lib\rules\numeric.js:20:31
> Thu, 19 May 2016 07:05:23 GMT validator deprecated you tried to validate a number but this library (validator.js) validates strings only. Please update your code as this will be an error soon. at node_modules\@relekang\validator\lib\rules\numeric.js:24:73
> Thu, 19 May 2016 07:05:23 GMT validator deprecated you tried to validate a number but this library (validator.js) validates strings only. Please update your code as this will be an error soon. at node_modules\@relekang\validator\lib\rules\numeric.js:29:59
> Thu, 19 May 2016 07:05:23 GMT validator deprecated you tried to validate a number but this library (validator.js) validates strings only. Please update your code as this will be an error soon. at node_modules\@relekang\validator\lib\rules\numeric.js:34:59

when my testing data contain a **string** value, but validator expects a **numeric** one.
Example of validation rule
`investment: {
    required: true,
    numeric: {integerOnly: true, min: 0, max: 9999999},
  },`

I would expect that I get error from validator about wrong format, not this warning.

**Comment by relekang** [comment]
Fixed by b25d802e2354e1e3c15582e64f6df6421606398b
