### ISSUE TITLE
Parsing zero value

### ISSUE THREAD

**Issue by PeterCervienka** [relekang/validator#21]
Required.js returns error when a value is numerical zero. The problem is probably because of `!!value`, which returns `false`, when value is `0`

+ add tests for value zero

https://github.com/relekang/validator/blob/master/src/rules/required.js#L11

**Comment by relekang** [comment]
Thanks, should be fixed in [v0.8.0](https://github.com/relekang/validator/blob/master/changelog.md#080-2016-05-23) ✌️
